PUT localhost:8088/api/point
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QudGVzdCIsInJvbGVzIjpbIlVTRVIiXSwiaWF0IjoxNTc4NDgxOTc4LCJleHAiOjE1NzkwODY3Nzh9.lEyedsAsthp1z_fbLZrVhFrzitYY4GMujAaUyXE7ym9u0aiKKKkFdovBTeN6Uls_-IAEu2wGcm-f6dqrbqAPYA

{
	"x": "1",
	"y": "2",
	"r": "1"
}

###