PUT localhost:8088/api/point
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJrdWxiYWtvMjAwMEBtYWlsLnJ1Iiwicm9sZXMiOlsiVVNFUiJdLCJpYXQiOjE1NzgzNTIzNDgsImV4cCI6MTU3ODk1NzE0OH0.ydTYxXhKiztEzz81lvuKq4oy0RUsqKlZU0WottD-5q2MDmTuyHrApOsEzRjwBgEi8wyYmU124U9sywtEmplSpg

{
	"x": "1",
	"y": "2",
	"r": "1"
}

###